<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Entrar | Health Admin</title>
    <style>
        *{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 85% 15%,#0d7d81 0,transparent 30%),linear-gradient(135deg,#061a31,#0a3f54);font-family:Arial,sans-serif;color:#10243c}.card{width:min(100%,430px);border-radius:18px;background:#fff;padding:40px;box-shadow:0 30px 80px rgba(0,0,0,.3)}.brand{display:flex;align-items:center;gap:12px;margin-bottom:32px;font-weight:800;letter-spacing:.08em}.mark{display:grid;width:44px;height:44px;place-items:center;border-radius:12px;background:linear-gradient(135deg,#77e2c9,#10a99f);color:#071b32}h1{margin:0 0 8px;font-size:28px}p{margin:0 0 28px;color:#6b7b8c}label{display:block;margin:18px 0 7px;font-size:13px;font-weight:700}input[type=email],input[type=password]{width:100%;height:48px;border:1px solid #dce8ed;border-radius:10px;padding:0 14px;font-size:15px;outline:none}input:focus{border-color:#10a99f;box-shadow:0 0 0 3px rgba(16,169,159,.12)}.remember{display:flex;align-items:center;gap:8px;margin:16px 0 22px;color:#657688;font-size:13px}button{width:100%;height:50px;border:0;border-radius:10px;background:#075b68;color:#fff;font-size:15px;font-weight:800;cursor:pointer}.error{border-radius:9px;background:#fff0f0;color:#a32121;padding:11px 13px;font-size:13px}.back{display:block;margin-top:22px;color:#687b8c;text-align:center;font-size:13px;text-decoration:none}
    </style>
</head>
<body><main class="card"><div class="brand"><span class="mark">H</span><span>HEALTH ADMIN</span></div><h1>Acesse sua plataforma</h1><p>Entre com suas credenciais administrativas.</p>@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('login.store') }}">@csrf<label for="email">E-mail</label><input id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" required autofocus><label for="password">Senha</label><input id="password" name="password" type="password" autocomplete="current-password" required><label class="remember"><input type="checkbox" name="remember" value="1"> Manter conectado</label><button type="submit">Entrar na plataforma</button></form><a class="back" href="https://aspti.com.br/healyh/">← Voltar ao site HEALYH</a></main></body>
</html>
